"""Shared Pydantic models and helpers."""

from .common import (
    ApiModel,
    ArxivSearchResponse,
    Author,
    AuthorListResponse,
    AuthorProfile,
    BatchAuthorResponse,
    BatchPaperResponse,
    BulkSearchResponse,
    CoreSearchResponse,
    Paper,
    PaperAuthorListResponse,
    PaperListResponse,
    RecommendationResponse,
    SearchResponse,
    SemanticSearchResponse,
    SnippetResult,
    SnippetSearchResponse,
    dump_jsonable,
)
from .tools import TOOL_INPUT_MODELS

__all__ = [
    "ApiModel",
    "ArxivSearchResponse",
    "Author",
    "AuthorListResponse",
    "AuthorProfile",
    "BatchAuthorResponse",
    "BatchPaperResponse",
    "BulkSearchResponse",
    "CoreSearchResponse",
    "Paper",
    "PaperAuthorListResponse",
    "PaperListResponse",
    "RecommendationResponse",
    "SearchResponse",
    "SemanticSearchResponse",
    "SnippetResult",
    "SnippetSearchResponse",
    "TOOL_INPUT_MODELS",
    "dump_jsonable",
]
